# Generated by Django 2.2.6 on 2019-10-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191024_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='catagory',
            field=models.CharField(choices=[('Regular_Pizza', 'PIZZA_R'), ('Sicilian_Pizza', 'PIZZA_S'), ('Subs', 'SUB'), ('Pasta', 'PASTA'), ('Salad', 'SALAD'), ('Dinner_Plate', 'DIN_PLATE')], max_length=120),
        ),
    ]
