# Generated by Django 2.2.6 on 2019-10-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191024_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='catagory',
            field=models.CharField(choices=[('Pizza Regular', 'PIZZA_REGULAR'), ('Pizza Sicilian', 'PIZZA_SICILIAN'), ('Subs', 'SUB'), ('Pasta', 'PASTA'), ('Salad', 'SALAD'), ('Dinner Plate', 'DINNER_PLATE')], max_length=120),
        ),
    ]
